# Generated by Django 4.2.2 on 2023-06-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_booking_token'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_booking',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('remarks__in', ['Pending', 'Completed', 'Missed by student'])), fields=('student', 'slot'), name='unique_booking'),
        ),
    ]
