# Generated by Django 4.2.2 on 2023-06-21 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0009_availableslot_unique_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slots.leave')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slots.availableslot')),
            ],
        ),
        migrations.AddField(
            model_name='availableslot',
            name='leaves',
            field=models.ManyToManyField(through='slots.LeaveSlot', to='slots.leave'),
        ),
        migrations.AddField(
            model_name='leave',
            name='slots',
            field=models.ManyToManyField(through='slots.LeaveSlot', to='slots.availableslot'),
        ),
    ]
